# k8s/overlays/local/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: mcp-servers-config
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: llm-server
  - path: milvus-patch.yaml
    target:
      kind: Deployment
      name: milvus-standalone
  - path: rag-server-patch.yaml
    target:
      kind: Deployment
      name: rag-server
