# k8s/overlays/local/rag-server-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-server
  namespace: retail-ai-demo
spec:
  template:
    spec:
      containers:
        - name: rag-server
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: "1"
              memory: 2Gi
