# k8s/overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - imagestream.yaml
  - buildconfig.yaml
  - inferenceservice-granite.yaml
  - model-pvc.yaml
  - route-granite.yaml

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: mcp-servers-config
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: llm-server
