# k8s/overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit from the base configuration
bases:
- ../../base

# Apply patches for the production environment
patchesStrategicMerge:
- configmap-patch.yaml
