apiVersion: v1
kind: Service
metadata:
  name: rag-server
  namespace: retail-ai-demo
  labels:
    app: rag-server
spec:
  selector:
    app: rag-server
  ports:
  - name: http
    protocol: TCP
    port: 8002
    targetPort: 8002
