apiVersion: v1
kind: Service
metadata:
  name: search-server
  namespace: retail-ai-demo
  labels:
    app: search-server
spec:
  selector:
    app: search-server
  ports:
  - name: http
    protocol: TCP
    port: 8003
    targetPort: 8003