apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-data
  namespace: retail-ai-demo
  labels:
    app: milvus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
