apiVersion: batch/v1
kind: Job
metadata:
  name: milvus-primer-job
  namespace: meridian-demo
spec:
  template:
    spec:
      containers:
      - name: primer
        image: image-registry.openshift-image-registry.svc:5000/meridian-demo/meridian-retail-ai:latest
        command: ["python", "scripts/prime_database.py"]
        envFrom:
        - secretRef:
            name: meridian-secrets
      restartPolicy: Never
  backoffLimit: 4