apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: streamlit-ui
  namespace: retail-ai-demo
  labels:
    app: streamlit-ui
spec:
  to:
    kind: Service
    name: streamlit-ui
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
