# k8s/base/secret.yaml
# This manifest creates an opaque secret.
# You must create this secret in your cluster with the actual base64-encoded API key.
# Example: kubectl create secret generic mcp-servers-secrets --from-literal=TAVILY_API_KEY='your_key_here' -n retail-ai-demo
apiVersion: v1
kind: Secret
metadata:
  name: mcp-servers-secrets
  namespace: retail-ai-demo
type: Opaque
data:
  # The key should be base64 encoded. 'your_key_here' -> 'eW91cl9rZXlfaGVyZQ=='
  TAVILY_API_KEY: "" 
